services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: cheese-password
      POSTGRES_USER: postgres
      POSTGRES_DB: cheese
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    environment:
      DB_URL: jdbc:postgresql://database:5432/cheese
      DB_USERNAME: postgres
      DB_PASSWORD: cheese-password
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
