package com.cheese.backend.entity;

import com.cheese.backend.enums.CheeseColor;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Cheese {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    // Autogenerated cheese ID
    private Long id;

    // Cheese name
    private String name;

    // Price per kilo
    private float price;

    // Cheese color
    @Enumerated(EnumType.STRING)
    private CheeseColor color;

    // Image name
    private String imageName;

    // Image type
    private String imageType;

    @Lob
    // Blob of the image
    private byte[] imageBlob;

    @Transient
    private String imageData;
}
